name: licenseGenerator

on:
  push:
    branches:
      - main

jobs:
  run:
    name: Generate License
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.4.0

      - name: Generate License
        uses: ./
        with:
          path: LICENSE.txt
          type: MIT
          year: 2019
          author: yi_Xu

      - name: Show License
        run: |
          cat LICENSE.txt
